parameters:
#    ez_systems_cookbook.example.class: EzSystems\CookbookBundle\Example

services:
#    ez_systems_cookbook.example:
#        class: %ez_systems_cookbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
