parameters:
#    ez_systems_cook_book.example.class: EzSystems\CookBookBundle\Example

services:
#    ez_systems_cook_book.example:
#        class: %ez_systems_cook_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
